using System.Linq;
using Content.Client.Message;
using Content.Shared.BombDefusal;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.BombDefusal.Scanner;

[GenerateTypedNameReferences]
public sealed partial class BombScannerMenu : DefaultWindow
{
    public BombScannerMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(BombRuleSet? ruleSet)
    {
        TabContainer.RemoveAllChildren();

        if (ruleSet == null)
        {
            SerialLabel.Text = "No scanned bomb data.";
            return;
        }

        SerialLabel.Text = $"Scanned Bomb Serial: {ruleSet.SerialNumber}  |  Modules: {ruleSet.ModuleCount}";

        foreach (var kvp in ruleSet.ModuleRules.OrderBy(k => k.Key))
        {
            var moduleRules = kvp.Value;
            var tabContent = string.Join("\n", moduleRules.RuleLines);
            var tabControl = CreateRichTextTab(tabContent);
            TabContainer.AddChild(tabControl);
            TabContainer.SetTabTitle(TabContainer.ChildCount - 1, moduleRules.ModuleName);
        }
    }

    private static ScrollContainer CreateRichTextTab(string content)
    {
        var scroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            HScrollEnabled = false,
        };

        var richText = new RichTextLabel
        {
            Margin = new Thickness(8),
            HorizontalExpand = true,
        };
        richText.Text = content;

        scroll.AddChild(richText);
        return scroll;
    }
}
