using System.Linq;
using Content.Client.BombDefusal.Modules;
using Content.Shared.BombDefusal;
using Content.Shared.BombDefusal.Modules;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.BombDefusal;

[GenerateTypedNameReferences]
public sealed partial class BombDefusalMenu : DefaultWindow
{
    /// <summary>
    /// Fired when the player interacts with a module.
    /// Args: (moduleIndex, action)
    /// </summary>
    public event Action<int, BombModuleAction>? OnModuleInteraction;

    private readonly List<BaseModuleControl> _moduleControls = new();

    public BombDefusalMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(BombDefusalUiState state)
    {
        // Update header
        SerialLabel.Text = $"SERIAL: {state.SerialNumber}";

        var minutes = (int) state.RemainingTime / 60;
        var seconds = (int) state.RemainingTime % 60;
        var timeStr = $"{minutes:D2}:{seconds:D2}";
        TimerLabel.Text = timeStr;

        // Color timer based on remaining time
        if (state.RemainingTime <= 30)
            TimerLabel.FontColorOverride = Color.FromHex("#ff2222");
        else if (state.RemainingTime <= 60)
            TimerLabel.FontColorOverride = Color.FromHex("#ff6644");
        else
            TimerLabel.FontColorOverride = Color.FromHex("#d0d0d0");

        // Visual strike markers: filled circles for strikes, empty for remaining
        var strikeChars = new List<string>();
        for (var i = 0; i < state.MaxStrikes; i++)
        {
            strikeChars.Add(i < state.Strikes ? "✕" : "○");
        }
        StrikesLabel.Text = string.Join(" ", strikeChars);

        // Color the strikes label based on count
        StrikesLabel.FontColorOverride = state.Strikes switch
        {
            0 => Color.FromHex("#cc3333"),
            1 => Color.FromHex("#ff4444"),
            2 => Color.FromHex("#ff2222"),
            _ => Color.FromHex("#ff0000"),
        };

        // Check for defusal
        if (!state.IsActive && state.Modules.All(m => m.IsSolved))
        {
            StatusPanel.Visible = true;
            StatusLabel.Text = Loc.GetString("bomb-defusal-defused");
        }
        else
        {
            StatusPanel.Visible = false;
        }

        // Create or update module controls
        if (_moduleControls.Count != state.Modules.Count)
        {
            RebuildModuleGrid(state);
        }
        else
        {
            for (var i = 0; i < state.Modules.Count; i++)
            {
                _moduleControls[i].UpdateState(state.Modules[i]);
            }
        }
    }

    private void RebuildModuleGrid(BombDefusalUiState state)
    {
        ModuleGrid.RemoveAllChildren();
        _moduleControls.Clear();

        // Adjust columns based on module count
        ModuleGrid.Columns = state.Modules.Count <= 2 ? state.Modules.Count : 3;

        for (var i = 0; i < state.Modules.Count; i++)
        {
            var moduleState = state.Modules[i];
            var moduleIndex = i;

            var control = CreateModuleControl(moduleState, moduleIndex);
            _moduleControls.Add(control);

            // Wrap in a panel for consistent sizing
            var panel = new PanelContainer
            {
                Margin = new Thickness(1),
                HorizontalExpand = true,
                VerticalExpand = false,
            };

            panel.AddChild(control);
            ModuleGrid.AddChild(panel);
        }
    }

    private BaseModuleControl CreateModuleControl(BombDefusalModuleState moduleState, int moduleIndex)
    {
        BaseModuleControl control = moduleState switch
        {
            WiresModuleState => new WiresModuleControl(),
            SymbolsModuleState => new SymbolsModuleControl(),
            SimonSaysModuleState => new SimonSaysModuleControl(),
            CodewordsModuleState => new CodewordsModuleControl(),
            MazeModuleState => new MazeModuleControl(),
            MemoryModuleState => new MemoryModuleControl(),
            PasswordModuleState => new PasswordModuleControl(),
            MorseCodeModuleState => new MorseCodeModuleControl(),
            WhosOnFirstModuleState => new WhosOnFirstModuleControl(),
            _ => new WiresModuleControl(), // fallback
        };

        control.ModuleIndex = moduleIndex;
        control.OnAction += action => OnModuleInteraction?.Invoke(moduleIndex, action);
        control.UpdateState(moduleState);

        return control;
    }
}
