using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.BombDefusal.Manual;

[GenerateTypedNameReferences]
public sealed partial class BombDefusalManualMenu : DefaultWindow
{
    public BombDefusalManualMenu()
    {
        RobustXamlLoader.Load(this);
        PopulateTabs();
    }

    private void PopulateTabs()
    {
        // Tab 1: Wires
        var wiresTab = CreateRichTextTab("WIRES", GetWiresManualText());
        TabContainer.AddChild(wiresTab);
        TabContainer.SetTabTitle(0, "Wires");

        // Tab 2: Symbols
        var symbolsTab = CreateRichTextTab("SYMBOLS", GetSymbolsManualText());
        TabContainer.AddChild(symbolsTab);
        TabContainer.SetTabTitle(1, "Symbols");

        // Tab 3: The Button
        var buttonTab = CreateRichTextTab("THE BUTTON", GetButtonManualText());
        TabContainer.AddChild(buttonTab);
        TabContainer.SetTabTitle(2, "The Button");

        // Tab 4: Simon Says
        var simonTab = CreateRichTextTab("SIMON SAYS", GetSimonSaysManualText());
        TabContainer.AddChild(simonTab);
        TabContainer.SetTabTitle(3, "Simon Says");

        // Tab 5: Codewords
        var codewordsTab = CreateRichTextTab("CODEWORDS", GetCodewordsManualText());
        TabContainer.AddChild(codewordsTab);
        TabContainer.SetTabTitle(4, "Codewords");
    }

    private static ScrollContainer CreateRichTextTab(string _title, string content)
    {
        var scroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        var richText = new RichTextLabel
        {
            Margin = new Thickness(8),
        };
        richText.SetMessage(content);

        scroll.AddChild(richText);
        return scroll;
    }

    private static string GetWiresManualText()
    {
        return @"[bold][color=#ff4444]BOMB DEFUSAL MANUAL — WIRES[/color][/bold]

A bomb module will have 3 to 6 colored wires.
Only ONE wire needs to be cut to disarm the module.
Wire colors: [color=#ff3333]Red[/color], [color=#3366ff]Blue[/color], [color=#ffdd33]Yellow[/color], [color=#eeeeee]White[/color], [color=#888888]Black[/color]

[bold][color=#ffaa00]3 WIRES:[/color][/bold]
• If there are no red wires, cut the second wire.
• Otherwise, if the last wire is white, cut the last wire.
• Otherwise, if there is more than one blue wire, cut the last blue wire.
• Otherwise, cut the last wire.

[bold][color=#ffaa00]4 WIRES:[/color][/bold]
• If there is more than one red wire AND the serial number's last digit is odd, cut the last red wire.
• Otherwise, if the last wire is yellow and there are no red wires, cut the first wire.
• Otherwise, if there is exactly one blue wire, cut the first wire.
• Otherwise, if there is more than one yellow wire, cut the last wire.
• Otherwise, cut the second wire.

[bold][color=#ffaa00]5 WIRES:[/color][/bold]
• If the last wire is black AND the serial number's last digit is odd, cut the fourth wire.
• Otherwise, if there is exactly one red wire and more than one yellow wire, cut the first wire.
• Otherwise, if there are no black wires, cut the second wire.
• Otherwise, cut the first wire.

[bold][color=#ffaa00]6 WIRES:[/color][/bold]
• If there are no yellow wires AND the serial number's last digit is odd, cut the third wire.
• Otherwise, if there is exactly one yellow wire and more than one white wire, cut the fourth wire.
• Otherwise, if there are no red wires, cut the last wire.
• Otherwise, cut the fourth wire.";
    }

    private static string GetSymbolsManualText()
    {
        return @"[bold][color=#ff4444]BOMB DEFUSAL MANUAL — SYMBOLS[/color][/bold]

Four symbols are displayed on buttons. Press them in the correct order.

Find the column below that contains ALL four of the symbols on the bomb.
Press the symbols in the order they appear in that column (top to bottom).

[bold][color=#ffaa00]COLUMN 1:[/color][/bold]  Ω  Ψ  Ξ  Φ  Σ  Δ  Π
[bold][color=#ffaa00]COLUMN 2:[/color][/bold]  Θ  Ω  Π  Λ  Γ  Σ  ℌ
[bold][color=#ffaa00]COLUMN 3:[/color][/bold]  ℘  ℜ  Λ  ℑ  ℵ  Ξ  Γ
[bold][color=#ffaa00]COLUMN 4:[/color][/bold]  ♠  ♣  ℑ  ♦  ♥  Ψ  ℜ
[bold][color=#ffaa00]COLUMN 5:[/color][/bold]  ★  ♥  ☆  ♠  ♣  ◆  ◇
[bold][color=#ffaa00]COLUMN 6:[/color][/bold]  ♠  Θ  ▲  ▼  ★  ℘  ☆

[italic]Note: Only one column will contain all four symbols shown on the bomb.[/italic]";
    }

    private static string GetButtonManualText()
    {
        return @"[bold][color=#ff4444]BOMB DEFUSAL MANUAL — THE BUTTON[/color][/bold]

A colored button with a text label. Follow the rules to determine what to do.

[bold][color=#ffaa00]FOLLOW THESE RULES IN ORDER:[/color][/bold]

1. If the button is [color=#3366ff]blue[/color] and the label says ""ABORT"": [bold]HOLD[/bold] the button.
2. If the label says ""DETONATE"": [bold]TAP[/bold] the button (press and release immediately).
3. If the button is [color=#eeeeee]white[/color]: [bold]HOLD[/bold] the button.
4. If the button is [color=#ff3333]red[/color] and the label says ""HOLD"": [bold]TAP[/bold] the button.
5. Otherwise: [bold]HOLD[/bold] the button.

[bold][color=#ffaa00]IF YOU ARE HOLDING:[/color][/bold]

A colored strip will appear. Release the button based on the strip color:
• [color=#3366ff]Blue[/color] strip: Release when the timer has a [bold]4[/bold] in any position.
• [color=#eeeeee]White[/color] strip: Release when the timer has a [bold]1[/bold] in any position.
• [color=#ffdd33]Yellow[/color] strip: Release when the timer has a [bold]5[/bold] in any position.
• [color=#ff3333]Red[/color] strip: Release when the timer has a [bold]1[/bold] in any position.";
    }

    private static string GetSimonSaysManualText()
    {
        return @"[bold][color=#ff4444]BOMB DEFUSAL MANUAL — SIMON SAYS[/color][/bold]

Colored lights flash in a sequence. Press the REMAPPED color buttons.
The mapping changes based on the serial number and current strikes.

[bold][color=#ffaa00]IF THE SERIAL NUMBER CONTAINS A VOWEL (A,E,I,O,U):[/color][/bold]

[bold]0 Strikes:[/bold]
  [color=#ff3333]Red[/color] → [color=#3366ff]Blue[/color] | [color=#3366ff]Blue[/color] → [color=#ff3333]Red[/color] | [color=#33ff33]Green[/color] → [color=#ffff33]Yellow[/color] | [color=#ffff33]Yellow[/color] → [color=#33ff33]Green[/color]

[bold]1 Strike:[/bold]
  [color=#ff3333]Red[/color] → [color=#ffff33]Yellow[/color] | [color=#3366ff]Blue[/color] → [color=#33ff33]Green[/color] | [color=#33ff33]Green[/color] → [color=#3366ff]Blue[/color] | [color=#ffff33]Yellow[/color] → [color=#ff3333]Red[/color]

[bold]2 Strikes:[/bold]
  [color=#ff3333]Red[/color] → [color=#33ff33]Green[/color] | [color=#3366ff]Blue[/color] → [color=#ff3333]Red[/color] | [color=#33ff33]Green[/color] → [color=#ffff33]Yellow[/color] | [color=#ffff33]Yellow[/color] → [color=#3366ff]Blue[/color]

[bold][color=#ffaa00]IF THE SERIAL NUMBER DOES NOT CONTAIN A VOWEL:[/color][/bold]

[bold]0 Strikes:[/bold]
  [color=#ff3333]Red[/color] → [color=#3366ff]Blue[/color] | [color=#3366ff]Blue[/color] → [color=#ffff33]Yellow[/color] | [color=#33ff33]Green[/color] → [color=#33ff33]Green[/color] | [color=#ffff33]Yellow[/color] → [color=#ff3333]Red[/color]

[bold]1 Strike:[/bold]
  [color=#ff3333]Red[/color] → [color=#ff3333]Red[/color] | [color=#3366ff]Blue[/color] → [color=#3366ff]Blue[/color] | [color=#33ff33]Green[/color] → [color=#ffff33]Yellow[/color] | [color=#ffff33]Yellow[/color] → [color=#33ff33]Green[/color]

[bold]2 Strikes:[/bold]
  [color=#ff3333]Red[/color] → [color=#ffff33]Yellow[/color] | [color=#3366ff]Blue[/color] → [color=#33ff33]Green[/color] | [color=#33ff33]Green[/color] → [color=#3366ff]Blue[/color] | [color=#ffff33]Yellow[/color] → [color=#ff3333]Red[/color]

[italic]Each stage adds one more flash. Replay the entire sequence each stage.[/italic]";
    }

    private static string GetCodewordsManualText()
    {
        return @"[bold][color=#ff4444]BOMB DEFUSAL MANUAL — CODEWORDS[/color][/bold]

Six words are displayed. Select the correct codeword.

Find the column that contains [bold]2 or more[/bold] of the displayed words.
The answer is the [bold]first word[/bold] in that column that appears in the display.

[bold][color=#ffaa00]COLUMN A:[/color][/bold] ALPHA, BRAVO, CHARLIE, DELTA, ECHO, FOXTROT
[bold][color=#ffaa00]COLUMN B:[/color][/bold] GOLF, HOTEL, INDIA, JULIET, KILO, LIMA
[bold][color=#ffaa00]COLUMN C:[/color][/bold] MIKE, NOVEMBER, OSCAR, PAPA, QUEBEC, ROMEO
[bold][color=#ffaa00]COLUMN D:[/color][/bold] SIERRA, TANGO, UNIFORM, VICTOR, WHISKEY, XRAY
[bold][color=#ffaa00]COLUMN E:[/color][/bold] YANKEE, ZULU, NINER, ZERO, CIPHER, AGENT
[bold][color=#ffaa00]COLUMN F:[/color][/bold] SECTOR, VECTOR, SIGNAL, BEACON, STATIC, CIPHER

[bold][color=#ffaa00]STEPS:[/color][/bold]
1. The defuser reads all 6 words.
2. Find which column has 2+ words from the list.
3. Of those matching words, the FIRST one in the column order is the answer.
4. Tell the defuser to select that word.

[italic]Note: If multiple columns match, use the first column alphabetically (A before B, etc).[/italic]";
    }
}
